ALTER TABLE public.labels ALTER COLUMN clip_offset_x TYPE DOUBLE PRECISION;
ALTER TABLE public.labels ALTER COLUMN clip_offset_y TYPE DOUBLE PRECISION;
ALTER TABLE public.labels ALTER COLUMN clip_width TYPE DOUBLE PRECISION;
ALTER TABLE public.labels ALTER COLUMN clip_height TYPE DOUBLE PRECISION;
