ALTER TABLE public.labels ADD COLUMN clip_offset_x INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.labels ADD COLUMN clip_offset_y INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.labels ADD COLUMN clip_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.labels ADD COLUMN clip_height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.labels ADD COLUMN page_number INTEGER NOT NULL DEFAULT 1;
ALTER TABLE public.labels ADD COLUMN clipped_image_url TEXT NOT NULL DEFAULT '';
