[project]
name = "processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markitdown[pdf, docx]",
    "geopandas>=1.0",
    "shapely>=2.0",
    "rasterio>=1.3",
    "Pillow>=10.0",
    "matplotlib>=3.7",
    "numpy>=1.24",
    "contextily>=1.4",
    "scipy>=1.11",
]
