import { ModeController } from "./modeController";
import { MouseInteractionController } from "./mouseInteractionController";
import { DragInteractionController } from "./dragInteractionController";
import { ToolManagerController } from "./tools/toolManagerController";
import { ImageCreateToolController } from "./tools/imageCreateToolController";
import { ImageMoveToolController } from "./tools/imageMoveToolController";
import { ImageResizeToolController } from "./tools/imageResizeToolController";
import { ImageRotateToolController } from "./tools/imageRotateToolController";
import { PolygonHitTestController } from "./tools/polygonHitTestController";
import { PolygonVertexMoveController } from "./tools/polygonVertexMoveController";
import { PolygonMoveController } from "./tools/polygonMoveController";
import { PolygonSelectController } from "./tools/polygonSelectController";
import { PolygonVertexAddController } from "./tools/polygonVertexAddController";
import { PolygonVertexDeleteController } from "./tools/polygonVertexDeleteController";
import { PolygonDeleteController } from "./tools/polygonDeleteController";
import { ProjectionController } from "./projectionController";
import { PdfUpdateController } from "./input/pdfUpdateController";
import { ImageUpdateController } from "./input/imageUpdateController";
import { BufferUpdateController } from "./input/bufferUpdateController";
import { CanvasSizeScaleController } from "./settings/canvasSizeScaleController";
import { ImagePropertyController } from "./imagePropertyController";
import { KeyboardInteractionController } from "./keyboardInteractionController";
import { TransformSessionController } from "./transformSessionController";

export type CanvasController = {
  modeController: ModeController;
  imageUpdateController: ImageUpdateController;
  mouseInteractionController: MouseInteractionController;
  dragInteractionController: DragInteractionController;
  toolManagerController: ToolManagerController;
  imageCreateToolController: ImageCreateToolController;
  imageMoveToolController: ImageMoveToolController;
  imageResizeToolController: ImageResizeToolController;
  imageRotateToolController: ImageRotateToolController;
  polygonHitTestController: PolygonHitTestController;
  polygonVertexMoveController: PolygonVertexMoveController;
  polygonMoveController: PolygonMoveController;
  polygonSelectController: PolygonSelectController;
  polygonVertexAddController: PolygonVertexAddController;
  polygonVertexDeleteController: PolygonVertexDeleteController;
  polygonDeleteController: PolygonDeleteController;
  projectionController: ProjectionController;
  pdfUpdateController: PdfUpdateController;
  bufferUpdateController: BufferUpdateController;
  canvasSizeScaleController: CanvasSizeScaleController;
  imagePropertyController: ImagePropertyController;
  keyboardInteractionController: KeyboardInteractionController;
  transformSessionController: TransformSessionController;
};
